version: 1

credentials:
    -   
        User: osadmin
        IdentityFile: ~/.ssh/jan_private_rsa
    -
        User: pi

groups:
    -
        Name: chaoshome
        Hosts:
            -
                Name: pollux
                HostName: pollux.chaoshome.local
                Port: 22
                Users: [osadmin]
            -
                Name: pihole
                HostName: pirategate.chaoshome.local
                Port: 22
                Users: [pi]
    -
        Name: stdpixel
        Hosts:
            -
                Name: stdvm-01
                HostName: stdvm-01.srv.stdpixel.com
                Port: 22
                Users: [osadmin]
