version: 1

credentials:
    -   
        User: osadmin
        IdentityFile: ~/.ssh/jan_private_rsa
    -
        User: pi

hosts:
    -
        Name: pollux
        HostName: pollux.chaoshome.local
        Port: 22
        users: [osadmin]
    -
        Name: pihole
        HostName: pirategate.chaoshome.local
        Port: 22
        users: [pi]
    -
        Name: stdvm-01
        HostName: stdvm-01.srv.stdpixel.com
        Port: 22
        users: [osadmin]
